### ISSUE TITLE
ReactNativeJS: { [TypeError: undefined is not an object (evaluating 'h.paymentRequestWithAndroidPay')]

### ISSUE THREAD

**Issue by SimoneLSK** [expo/expo-payments-stripe#2]
```
Platform : AN 
ENV: Signed APK
SDK: both 30 & 29 with expo-payments-stripe installed 
```

when execute `**Stripe.paymentRequestWithAndroidPayAsync()**` which caught error 
<img width="751" alt="screen shot 2018-09-19 at 4 02 39 am" src="https://user-images.githubusercontent.com/26976153/45713176-e7179f00-bbc0-11e8-867f-49cfedfc018a.png">

I am not sure if it is a bug or because my app's payment function still has not approved by Google.

```
async componentWillMount(){
        await Stripe.setOptionsAsync({
            publishableKey: publishableKey, 
            androidPayMode: 'test', 
        });
}

makePayment = async (options) => {
    try{
        token = await Stripe.paymentRequestWithAndroidPayAsync(options);
    } catch (err) {
        console.log(err)
    }
}
```

Thanks

**Comment by esamelson** [comment]
Hi @SimoneLSK - are you using this module in an ExpoKit project, or vanilla React Native?

**Comment by SimoneLSK** [comment]
Hi @esamelson , 

Using this module with ExpoKit. 
When the apps running in **development mode** by expo start, I was able to call the **google payment sheet**.  
Its **only** not working with Signed APK. 


Procedure:
1. run `expo start `
2. run  `run... ` in android studio, (App installed on simulator)
3. execute `Stripe.paymentRequestWithAndroidPayAsync()`, (Payment Sheet Appeared)
4. run `expo publish` 
5. run `Generated Signed APK` in android studio
6. install APK and  execute `Stripe.paymentRequestWithAndroidPayAsync()` (No Payment Sheet Appeared)

**Comment by sjchmiela** [comment]
Hi @SimoneLSK! Could you please verify if instructions provided [here](https://github.com/expo/expo/issues/2087#issuecomment-414996822) resolve the issue?

**Comment by SimoneLSK** [comment]
Hi 
I am currently away from town 
Will try this when back 
Thanks

**Comment by heyaj19** [comment]
@sjchmiela  Its not working. I am facing the same issue - those proguard rules and settings are already in the build.gradle. 

It works fine  if I remove the stripe.publishableKey line out. But when its in there it doesn't work. Any suggestons?
