### ISSUE TITLE
Usage of this module and how to build a similar one?

### ISSUE THREAD

**Issue by hukid** [expo/expo-payments-stripe#4]
Hi, 

Is this a expo module that I can use in expo project without having to detach? I wonder how you do this given this module has dependencies on a native sdk (stripe)? 

If I have another native sdk, can I build it into expo in similar way? Thanks!

**Comment by sjchmiela** [comment]
Hey @hukid!

Unfortunately we don't support adding optional Expo modules to your applications without needing to detach. To use this module you'll still have to detach.

We intend to support building standalone applications with customized set of modules included in the future. 🙂 

When it comes to building your own universal module it's going to be possible soon. A new command for that has been recently merged into `expo-cli` (https://github.com/expo/expo-cli/pull/25). Short instructions to adding such module can be found [here](https://gist.github.com/sjchmiela/d6f093d1c1398419a15897eb97490242), but note they're a work-in-progress and were initially intended only for our internal use (so if you encounter any problems, just contact me directly eg. on expo-developers' slack). 🙂

**Comment by sjchmiela** [comment]
I hope I've answered your question, @hukid, I'll close this issue tentatively. 🙂

**Comment by hukid** [comment]
Hi, @sjchmiela 

Sorry for the late response! Thanks for your answer and glad to know you are working on it!
